apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-serv-zh
  namespace: zh938207
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-serv-zh
  template:
    metadata:
      labels:
        app: sql-serv-zh
    spec:
      containers:
      - name: sql-serv-zh
        image: ighost007/sql-serv-zh:latest
        ports:
        - containerPort: 3304
      imagePullSecrets:
      - name: my-docker-credentials
